image: "registry.roqua.nl/roqua/docker-base-images:ruby-2.7-builder"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v

test:
  stage: test
  script:
    - bundle install --path vendor
    - bundle exec nanoc compile
    - bundle exec nanoc check ilinks
  artifacts:
    paths:
      - output
  except:
    - master

deploy:
  stage: deploy
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - bundle install --path vendor
    - bundle exec nanoc compile
    - mv output public
    - rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete ./public/ $SSH_USER@$SERVER_IP:~/roqua_frontpage/html
  artifacts:
    paths:
      - public
  only:
    - master
