image: "registry.roqua.nl/roqua/docker-base-images:ruby-2.6-builder"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v

test:
  stage: test
  script:
    - bundle install --path vendor
    - bundle exec nanoc compile
  artifacts:
    paths:
      - output
  except:
    - master

pages:
  stage: deploy
  script:
    - bundle install --path vendor
    - bundle exec nanoc compile
    - mv output public
  artifacts:
    paths:
      - public
  only:
    - master
