name: Build site

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - run: bundle exec nanoc compile
      - run: bundle exec nanoc check ilinks
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: output

      - name: Rsync Deployer
        uses: imajeetyadav/rsync-deployer@1.0.0
        with:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE_PATH: "./output/"
          TARGET_PATH: "~/roqua_frontpage/html/"
          PORT: 22
          RSYNC_PARAMETERS: ""
          DELETE_OPTION: "true"
          EXCLUDE_LIST: ".git, .github"
